### ISSUE TITLE
Ввести тег - наличие русификации

### ISSUE THREAD

**Issue by nnsns** [Newbilius/GamesRevival#105]
Многие игры, попутно с портированием, обзавелись русификаторами.
Это было-бы неплохо помечать отдельным тегом.

**Comment by Newbilius** [comment]
Выкладывать все русификаторы - точно миссия не этого сайта ;-)

Но вот ввести тег "поддерживает русификацию" пожалуй стоит: многие порты и моды с русскими версиями не совместимы,

**Comment by nnsns** [comment]
Поясню на примере.
Увидел в списке Imperium Galactica. Прошел по ссылке на гитхаб и увидел, что там теперь вполне официально поддерживается русский язык. КМК, это важная информация.
По крайне мере, теперь я точно в нее поиграю. :-)

**Comment by Newbilius** [comment]
Хе, т.е. у нас две ситуации - поддерживает русскую версию или вместе с модом/портом поставляется и локализация. Да, согласен, стоит обе ситуации отмечать, возможно одним и тем же тегом)

**Comment by Newbilius** [comment]
И по поводу реализации: теги может добавить любой желающий, просто идём в файл tags нужного порта - и с новой строки вписываем тег "русский язык" :)

Для начала - добавил для Dune 2: Legacy
https://github.com/Newbilius/GamesRevival/blob/master/DATA/Dune_2/Dune_Legacy/tags.txt
