### ISSUE TITLE
Официальный 'remaster'

### ISSUE THREAD

**Issue by SiberianGRemlin** [Newbilius/GamesRevival#164]
Предлагаю превратить это в ярлык (tag), а в названии писать официальное наименование, например, «Forsaken Remastered». Так нагляднее, улучшает индексирование в поисковиках, а также делает более явным появление в разделе «Случайный мод» – сейчас там часто попадаются разные игры с одним и тем же названием «Официальный ремастер». Для тех, кто не знает наизусть, как выглядят все игры на данном сайте при их запуске, это создаёт трудности в восприятии данного раздела.

**Comment by Newbilius** [comment]
Хорошая идея. В принципе текущий тег "ремастер" и подразумевал "официальные ремастеры", да. Чуть попозже переименую теги и сами ремастеры

**Comment by Newbilius** [comment]
Готово :)
