### ISSUE TITLE
Новые фичи

### ISSUE THREAD

**Issue by shikulja** [Newbilius/GamesRevival#189]
Может я не заметил.

Есть разные хаки, и врапперы, которые заточены под множество игр, или серий игр.
(например последний DDHack для warcraft 2 что я добавил)
Поэтому хотелось бы увидеть привязку к нескольким играм.

2. Нет каких нибудь удобных строк типа - 
- версия\дата текущая
-  проект завершен\в разработке и т.д.
(ну типа как на википедии)

**Comment by Newbilius** [comment]
По поводу врапперов и массовых вещейтипа ScummVM - я пока в размышлении, как их оформить в рамках сайта.

Версию добавлять, имхо, нет смысла (их нужно регулярно обновлять, а это вряд ли кто-то будет делать), а вот решить это дело тегами надо. Сейчас есть теги "заброшен" и "неиграбелен", но надо подумать, насколько оно удобно - может какие-то теги добавить, какие-то заменить.

**Comment by Newbilius** [comment]
Сдела раздел с утилитами: появляется в случае, если в поиске не нашёл нужную игру + кнопка на главной странице
