### ISSUE TITLE
Описание сайта в статье на хабре

### ISSUE THREAD

**Issue by KosMos-pv** [Newbilius/GamesRevival#241]
На канале Old-hard в видео про запуск старых игр на современном ПК есть ссылка на статью на GeekTimes (ныне хабр). Хотя ссылка на сайт вполне рабочая, но в статье указано, что сайт Games Revival давно не обновлялся и source-портов там очень мало. Но теперь это уже неактуальная информация. Если статью на хабре можно отредактировать спустя такое время, предлагаю исправить описание для Games Revival.
https://habr.com/ru/post/365881/

**Comment by Newbilius** [comment]
Спасибо! Хорошая мысль, исправлю :)

**Comment by Newbilius** [comment]
Информация добавлена)
