### ISSUE TITLE
Игровые жанры

### ISSUE THREAD

**Issue by Newbilius** [Newbilius/GamesRevival#28]
Для отображения в [списке игр ](https://www.gamesrevival.ru/games.html)и для поиска/фильтрации.

**Comment by Newbilius** [comment]
Пока надобность под вопросом

**Comment by firemdkfighter** [comment]
> Пока надобность под вопросом

Чем больше игр будет - тем сложнее будет их просмотр. Считаю, что список жанров нужен

**Comment by kcalbCube** [comment]
Да. Определенно нужен. Возможно нужно обязывать писать жанр игры по шаблону Жанр: <название жанра>, после чего парсить страницы.

**Comment by Newbilius** [comment]
Добавил фильтрацию на странице списка игр (https://www.gamesrevival.ru/games.html)
