### ISSUE TITLE
Добавь отсутствующе обложи

### ISSUE THREAD

**Issue by Unknown8989** [Newbilius/GamesRevival#338]
![logo (bsaog)](https://user-images.githubusercontent.com/95621354/207871190-d640dc17-91a2-4faa-908b-a42cbd78b31a.jpg)
![logo (cd)](https://user-images.githubusercontent.com/95621354/207871204-8564158b-ffdb-4f6c-aea3-8149dc24dba7.jpg)
![logo (ddihm)](https://user-images.githubusercontent.com/95621354/207871215-bcd7d4a6-97cd-4b2a-b7f6-f223fde06564.jpg)
![logo (ffviii)](https://user-images.githubusercontent.com/95621354/207871222-791c59a5-c8c8-44cc-9b7e-c454a02400e7.jpg)
![logo (pg)](https://user-images.githubusercontent.com/95621354/207871229-4bfc8b77-84df-46f8-a7b7-f4a65423fe67.jpg)
![logo (q4)](https://user-images.githubusercontent.com/95621354/207871233-6e84fb55-a40e-40b0-a3db-a4c2f45f1698.jpg)
![logo (rct2)](https://user-images.githubusercontent.com/95621354/207871243-f68e8bd1-7159-496d-88d0-168944bed1d0.jpg)
![logo (rfg)](https://user-images.githubusercontent.com/95621354/207871249-61320ea5-9756-43e4-b1cd-394ef4c42100.jpg)
![logo (roast)](https://user-images.githubusercontent.com/95621354/207871259-98f4f4fc-5e1b-401e-8603-19681591042a.jpg)
![logo (sof)](https://user-images.githubusercontent.com/95621354/207871262-87835ff3-86a5-4b88-8d11-e36d614e2474.jpg)
![logo (swxwa)](https://user-images.githubusercontent.com/95621354/207871273-e86f0149-4c50-4978-aa8d-feafeddde047.jpg)
![logo (ts)](https://user-images.githubusercontent.com/95621354/207871277-cf93f9a1-ef51-49fa-92a3-37b79186c0cc.jpg)
![logo (ttfs)](https://user-images.githubusercontent.com/95621354/207871287-d7e19b7d-4236-42fe-92b3-eb37403b22fc.jpg)

**Comment by Unknown8989** [comment]
Вот все обложки в архиве:
[logos.zip](https://github.com/Newbilius/GamesRevival/files/10237340/logos.zip)

**Comment by Newbilius** [comment]
О, огромное спасибо! На днях залью :)

**Comment by Newbilius** [comment]
Все обложки добавлены, в течение часа сайт обновится
