### ISSUE TITLE
Описание Daggerfall Unity (Duggerfall_Workshop)

### ISSUE THREAD

**Issue by korn3r** [Newbilius/GamesRevival#604]
https://www.gamesrevival.ru/games/Elder_Scrolls_II_Daggerfall/Duggerfall_Workshop/

1. Стоит тэг "Улучшенные текстуры", хотя это sourceport (если я правильно понял вашу терминологию относительно альтернативных движков). Улучшенные текстуры там тоже опционально есть, но именно доп опция к движку (наряду с доп квестами и доп локациями, которые тоже дополнениями к этому движку идут)
2. Стоит тэг windows, хотя оно "windows, linux и macos"

**Comment by Newbilius** [comment]
По пункту 1 - всё по задумке, если к порту или воссозданию движка можно подключить улушенные текстуры.
А по пункту 2 - поправил, спасибо, скоро обновится на сайте)
